<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="DADViewer.Tests\**\*.cs" />
        <EmbeddedResource Remove="DADViewer.Tests\**\*" />
        <None Remove="DADViewer.Tests\**\*" />
        <Page Remove="DADViewer.Tests\**\*.xaml" />
    </ItemGroup>
</Project>
